#include <stdio.h>
#include "ft_printf.h"

int main()
{
	void *ptr = NULL;

	printf ("%s \n", "############################## My printf ##############################");
	printf("\n\n");
	printf("\n\n");
	printf ("%s \n","  ██████╗██╗  ██╗ █████╗ ██████╗     ██╗ ██╗ ██████╗");
	printf ("%s \n"," ██╔════╝██║  ██║██╔══██╗██╔══██╗    ╚═╝██╔╝██╔════╝");
	printf ("%s \n"," ██║     ███████║███████║██████╔╝      ██╔╝ ██║     ");
	printf ("%s \n"," ██║     ██╔══██║██╔══██║██╔══██╗     ██╔╝  ██║     ");
	printf ("%s \n"," ╚██████╗██║  ██║██║  ██║██║  ██║    ██╔╝██╗╚██████╗");
	printf ("%s \n","  ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝    ╚═╝ ╚═╝ ╚═════╝");
	printf("\n\n");
	printf("Return value check for single char. Original return value is '%d'\n",  printf(" %c\n", 'x'));
	printf("Return value check for single char. Ftprintf return value is '%d'\n",  ft_printf(" %c\n", 'x'));
	printf("\n\n");
	printf("Return value check for NULL char. Original return value is '%d'\n", printf ("%c\n", (char)0));
	printf("Return value check for NULL char. Ftprintf return value is '%d'\n", ft_printf ("%c\n", (char)0));
	printf("\n\n");
	printf("Return value check for double single char %%c%%c. Original return value is '%d'\n", printf ("%c%c\n", 'a', 'a'));
	printf("Return value check for double single char %%c%%c. Ftprintf return value is '%d'\n", ft_printf ("%c%c\n", 'a', 'a'));
	printf("\n\n");
	printf("Return value check for str & NULL . Original return value is '%d'\n", printf ("%s\n", (char *)NULL));
	printf("Return value check for str & NULL. Ftprintf return value is '%d'\n", ft_printf ("%s\n", (char *)NULL));
	printf("\n\n");
	printf("Return value check for non printable ascii chars. Original return value is '%d'\n", printf("\001\002\007\v\010\f\r\n"));
	printf("Return value check for non printable ascii chars. Ftprintf return value is '%d'\n", ft_printf("\001\002\007\v\010\f\r\n"));
	printf("\n");
	printf("Return value check for %%%%c. Original return value is '%d'\n", printf ("%%c\n"));
	printf("Return value check for %%%%c. Ftprintf return value is '%d'\n", ft_printf ("%%c\n"));
	printf("\n\n");
	printf("Return value check for RAND char & str. Original return value is '%d'\n", printf("%c%%c%c%cc%%s%s\n", (char)0, 'y', 'y', "s"));
	printf("Return value check for RAND char & str. Ftprintf return value is '%d'\n", ft_printf("%c%%c%c%cc%%s%s\n", (char)0, 'y', 'y', "s"));
	printf("\n\n");
	printf("\n\n");
	printf ("%s \n","███████╗████████╗██████╗ ██╗███╗   ██╗ ██████╗ ███████╗    ██╗ ██╗███████╗");
	printf ("%s \n","██╔════╝╚══██╔══╝██╔══██╗██║████╗  ██║██╔════╝ ██╔════╝    ╚═╝██╔╝██╔════╝");
	printf ("%s \n","███████╗   ██║   ██████╔╝██║██╔██╗ ██║██║  ███╗███████╗      ██╔╝ ███████╗");
	printf ("%s \n","╚════██║   ██║   ██╔══██╗██║██║╚██╗██║██║   ██║╚════██║     ██╔╝  ╚════██║");
	printf ("%s \n","███████║   ██║   ██║  ██║██║██║ ╚████║╚██████╔╝███████║    ██╔╝██╗███████║");
	printf ("%s \n","╚══════╝   ╚═╝   ╚═╝  ╚═╝╚═╝╚═╝  ╚═══╝ ╚═════╝ ╚══════╝    ╚═╝ ╚═╝╚══════╝"); 
	printf("\n\n");

	printf("Return value check for strings. Should be %d, is %d\n", printf ("Strings: %s%c%s \n", "Hello", ' ', "World"), ft_printf ("Strings: %s%c%s \n", "Hello", ' ', "World"));
	printf("\n\n");
	printf("Return value check for strings. Should be %d, is %d\n", printf ("Strings: %s%c%c%d%s \n", "Hello", ' ', ' ', 1, "World"), ft_printf ("Strings: %s%c%c%d%s \n", "Hello", ' ', ' ', 1, "World"));
	printf("\n\n");
	printf("\n\n");
	printf ("%s \n"," ██████╗ ███████╗███████╗██╗███╗   ███╗ █████╗ ██╗     ███████╗    ██╗ ██╗██████╗ ");
	printf ("%s \n"," ██╔══██╗██╔════╝██╔════╝██║████╗ ████║██╔══██╗██║     ██╔════╝    ╚═╝██╔╝██╔══██╗");
	printf ("%s \n"," ██║  ██║█████╗  ███████╗██║██╔████╔██║███████║██║     ███████╗      ██╔╝ ██║  ██║");
	printf ("%s \n"," ██║  ██║██╔══╝  ╚════██║██║██║╚██╔╝██║██╔══██║██║     ╚════██║     ██╔╝  ██║  ██║");
	printf ("%s \n"," ██████╔╝███████╗███████║██║██║ ╚═╝ ██║██║  ██║███████╗███████║    ██╔╝██╗██████╔╝");
	printf ("%s \n"," ╚═════╝ ╚══════╝╚══════╝╚═╝╚═╝     ╚═╝╚═╝  ╚═╝╚══════╝╚══════╝    ╚═╝ ╚═╝╚═════╝ ");
	printf("\n\n");
	printf("Return value check for triple digits %%d%%d%%d. Original return value is %d\n", printf ("Digits: %d%d%d \n", 1, 33, 7));
	printf("Return value check for triple digits %%d%%d%%d. Ftprintf return value is %d\n", ft_printf ("Digits: %d%d%d \n", 1, 33, 7));
	printf("\n\n");
	printf("Return value check for longer single digit. Original return value is '%d'\n", printf ("Digits: %d\n", 1234567));
	printf("Return value check for longer single digit. Ftprintf return value is '%d'\n", ft_printf ("Digits: %d\n", 1234567));
	printf("\n\n");
	printf("Return value check for single digits %%d. Original return value is '%d'\n", printf ("%d\n", 1));
	printf("Return value check for single digits %%d. Ftprintf return value is '%d'\n", ft_printf ("%d\n", 1));
	printf("\n\n");
	printf("Return value check for double digits %%d%%d. Original return value is '%d'\n", printf ("%d%d\n", 1, 1));
	printf("Return value check for double digits %%d%%d. Ftprintf return value is '%d'\n", ft_printf ("%d%d\n", 1, 1));
	printf("\n\n");
	printf("Return value check for int MAX. Original return value is '%d'\n", printf("%d\n", INT_MAX));
	printf("Return value check for int MAX. Ftprintf return value is '%d'\n", ft_printf("%d\n", INT_MAX));
	printf("\n\n");
	printf("Return value check for int MIN. Original return value is '%d'\n", printf("%d\n", INT_MIN));
	printf("Return value check for int MIN. Ftprintf return value is '%d'\n", ft_printf("%d\n", INT_MIN));
	printf("\n\n");
	printf("\n\n");
	printf("\n\n");      
	printf ("%s \n","██╗███╗   ██╗████████╗███████╗ ██████╗ ███████╗██████╗ ███████╗    ██╗ ██╗██╗");
	printf ("%s \n","██║████╗  ██║╚══██╔══╝██╔════╝██╔════╝ ██╔════╝██╔══██╗██╔════╝    ╚═╝██╔╝██║");
	printf ("%s \n","██║██╔██╗ ██║   ██║   █████╗  ██║  ███╗█████╗  ██████╔╝███████╗      ██╔╝ ██║");
	printf ("%s \n","██║██║╚██╗██║   ██║   ██╔══╝  ██║   ██║██╔══╝  ██╔══██╗╚════██║     ██╔╝  ██║");
	printf ("%s \n","██║██║ ╚████║   ██║   ███████╗╚██████╔╝███████╗██║  ██║███████║    ██╔╝██╗██║");
	printf ("%s \n","╚═╝╚═╝  ╚═══╝   ╚═╝   ╚══════╝ ╚═════╝ ╚══════╝╚═╝  ╚═╝╚══════╝    ╚═╝ ╚═╝╚═╝");  
	printf("\n\n");    
	printf("Return value check for positive decimal integer %%i, 42. Original return value is '%d'\n", printf ("%i\n", 42));
	printf("Return value check for positive decimal integer %%i, 42. Ftprintf return value is '%d'\n", ft_printf ("%i\n", 42));
	printf("\n\n");    
	printf("Return value check for positive octal integer %%i, 052. Original return value is '%d'\n", printf ("%i\n", 052));
	printf("Return value check for positive octal integer %%i, 052. Ftprintf return value is '%d'\n", ft_printf ("%i\n", 052));
	printf("\n\n");
	printf("Return value check for negative octal integer %%i, -052. Original return value is '%d'\n", printf ("%i\n", -052));
	printf("Return value check for negative octal integer %%i, -052. Ftprintf return value is '%d'\n", ft_printf ("%i\n", -052));
	printf("\n\n");
	printf("Return value check for positive hexadecimal integer %%i, 0x2a. Original return value is '%d'\n", printf ("%i\n", 0x2a));
	printf("Return value check for positive hexadecimal integer %%i, 0x2a. Ftprintf return value is '%d'\n", ft_printf ("%i\n", 0x2a));
	printf("\n\n");
	printf("Return value check for negative hexadecimal integer %%i, -0x2a. Original return value is '%d'\n", printf ("%i\n", -0x2a));
	printf("Return value check for negative hexadecimal integer %%i, -0x2a. Ftprintf return value is '%d'\n", ft_printf ("%i\n", -0x2a));
	printf("\n\n");
	printf("\n\n");  
	printf ("%s \n","██╗   ██╗███╗   ██╗███████╗██╗ ██████╗ ███╗   ██╗███████╗██████╗     ██╗███╗   ██╗████████╗███████╗ ██████╗ ███████╗██████╗ ███████╗    ██╗ ██╗██╗   ██╗");
	printf ("%s \n","██║   ██║████╗  ██║██╔════╝██║██╔════╝ ████╗  ██║██╔════╝██╔══██╗    ██║████╗  ██║╚══██╔══╝██╔════╝██╔════╝ ██╔════╝██╔══██╗██╔════╝    ╚═╝██╔╝██║   ██║");
	printf ("%s \n","██║   ██║██╔██╗ ██║███████╗██║██║  ███╗██╔██╗ ██║█████╗  ██║  ██║    ██║██╔██╗ ██║   ██║   █████╗  ██║  ███╗█████╗  ██████╔╝███████╗      ██╔╝ ██║   ██║");
	printf ("%s \n","██║   ██║██║╚██╗██║╚════██║██║██║   ██║██║╚██╗██║██╔══╝  ██║  ██║    ██║██║╚██╗██║   ██║   ██╔══╝  ██║   ██║██╔══╝  ██╔══██╗╚════██║     ██╔╝  ██║   ██║");
	printf ("%s \n","╚██████╔╝██║ ╚████║███████║██║╚██████╔╝██║ ╚████║███████╗██████╔╝    ██║██║ ╚████║   ██║   ███████╗╚██████╔╝███████╗██║  ██║███████║    ██╔╝██╗╚██████╔╝");
	printf ("%s \n"," ╚═════╝ ╚═╝  ╚═══╝╚══════╝╚═╝ ╚═════╝ ╚═╝  ╚═══╝╚══════╝╚═════╝     ╚═╝╚═╝  ╚═══╝   ╚═╝   ╚══════╝ ╚═════╝ ╚══════╝╚═╝  ╚═╝╚══════╝    ╚═╝ ╚═╝ ╚═════╝ ");
	printf("\n\n");  
	printf("\n\n");
	printf("Return value check for positive unsigned int %%u. Original return value is '%d'\n", printf ("%u\n", 1));
	printf("Return value check for positive unsigned int %%u. Ftprintf return value is '%d'\n", ft_printf ("%u\n", 1));
	printf("\n\n");
	printf("Return value check for negative unsigned int %%u. Original return value is '%d'\n", printf ("%u\n", -1));
	printf("Return value check for negative unsigned int %%u. Ftprintf return value is '%d'\n", ft_printf ("%u\n", -1));
	printf("\n\n");
	printf("\n\n");
	printf("\n\n");  
	printf ("%s \n","██╗  ██╗███████╗██╗  ██╗ █████╗ ██████╗ ███████╗ ██████╗██╗███╗   ███╗ █████╗ ██╗         ██╗███╗   ██╗████████╗███████╗ ██████╗ ███████╗██████╗     ██╗ ██╗██╗  ██╗");
	printf ("%s \n","██║  ██║██╔════╝╚██╗██╔╝██╔══██╗██╔══██╗██╔════╝██╔════╝██║████╗ ████║██╔══██╗██║         ██║████╗  ██║╚══██╔══╝██╔════╝██╔════╝ ██╔════╝██╔══██╗    ╚═╝██╔╝╚██╗██╔╝");
	printf ("%s \n","███████║█████╗   ╚███╔╝ ███████║██║  ██║█████╗  ██║     ██║██╔████╔██║███████║██║         ██║██╔██╗ ██║   ██║   █████╗  ██║  ███╗█████╗  ██████╔╝      ██╔╝  ╚███╔╝ ");
	printf ("%s \n","██╔══██║██╔══╝   ██╔██╗ ██╔══██║██║  ██║██╔══╝  ██║     ██║██║╚██╔╝██║██╔══██║██║         ██║██║╚██╗██║   ██║   ██╔══╝  ██║   ██║██╔══╝  ██╔══██╗     ██╔╝   ██╔██╗ ");
	printf ("%s \n","██║  ██║███████╗██╔╝ ██╗██║  ██║██████╔╝███████╗╚██████╗██║██║ ╚═╝ ██║██║  ██║███████╗    ██║██║ ╚████║   ██║   ███████╗╚██████╔╝███████╗██║  ██║    ██╔╝██╗██╔╝ ██╗");
	printf ("%s \n","╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═════╝ ╚══════╝ ╚═════╝╚═╝╚═╝     ╚═╝╚═╝  ╚═╝╚══════╝    ╚═╝╚═╝  ╚═══╝   ╚═╝   ╚══════╝ ╚═════╝ ╚══════╝╚═╝  ╚═╝    ╚═╝ ╚═╝╚═╝  ╚═╝");
	printf("\n\n");  
	printf("Return value check for positive hex value %%x, 42. Original return value is '%d'\n", printf ("%x\n", 42));
	printf("Return value check for positive hex value %%x, 42. Ftprintf return value is '%d'\n", ft_printf ("%x\n", 42));
	printf("\n\n");
	printf("Return value check for positive hex values %%x%%x. Original return value is '%d'\n", printf ("%x%x\n", 111111111, 111));
	printf("Return value check for positive hex values %%x%%x. Ftprintf return value is '%d'\n", ft_printf ("%x%x\n", 111111111, 111));
	printf("\n\n");
	printf("Return value check for negative hex values %%X%%X. Original return value is '%d'\n", printf ("%X%X\n", -111111111, -111));
	printf("Return value check for negative hex values %%X%%X. Ftprintf return value is '%d'\n", ft_printf ("%X%X\n", -111111111, -111));
	printf("\n\n");
	printf("\n\n");  
	printf ("%s \n","██████╗  ██████╗ ██╗███╗   ██╗████████╗███████╗██████╗      █████╗ ██████╗ ██████╗ ██████╗ ███████╗███████╗███████╗    ██╗ ██╗██████╗ ");
	printf ("%s \n","██╔══██╗██╔═══██╗██║████╗  ██║╚══██╔══╝██╔════╝██╔══██╗    ██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔════╝██╔════╝██╔════╝    ╚═╝██╔╝██╔══██╗");
	printf ("%s \n","██████╔╝██║   ██║██║██╔██╗ ██║   ██║   █████╗  ██████╔╝    ███████║██║  ██║██║  ██║██████╔╝█████╗  ███████╗███████╗      ██╔╝ ██████╔╝");
	printf ("%s \n","██╔═══╝ ██║   ██║██║██║╚██╗██║   ██║   ██╔══╝  ██╔══██╗    ██╔══██║██║  ██║██║  ██║██╔══██╗██╔══╝  ╚════██║╚════██║     ██╔╝  ██╔═══╝ ");
	printf ("%s \n","██║     ╚██████╔╝██║██║ ╚████║   ██║   ███████╗██║  ██║    ██║  ██║██████╔╝██████╔╝██║  ██║███████╗███████║███████║    ██╔╝██╗██║     ");
	printf ("%s \n","╚═╝      ╚═════╝ ╚═╝╚═╝  ╚═══╝   ╚═╝   ╚══════╝╚═╝  ╚═╝    ╚═╝  ╚═╝╚═════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚══════╝╚══════╝    ╚═╝ ╚═╝╚═╝     ");
	printf("\n\n");  
	printf("\n\n");
	printf("Return value check for &ptr addr. Original return value is '%d'\n", printf ("%p\n", &ptr));
	printf("Return value check for &ptr addr. Ftprintf return value is '%d'\n", ft_printf ("%p\n", &ptr));
	printf("\n\n");
	printf("Return value check for ptr addr. Original return value is '%d'\n", printf ("%p\n", ptr));
	printf("Return value check for ptr addr. Ftprintf return value is '%d'\n", ft_printf ("%p\n", ptr));
	printf("\n\n");
	printf("Return value check for ptr addr and null char. Original return value is '%d'\n", printf ("%p\n", (char *)NULL));
	printf("Return value check for ptr addr and null char. Ftprintf return value is '%d'\n", ft_printf ("%p\n", (char *)NULL));
	printf("\n\n");
	printf("Return value check for ptr addr and empty str. Original return value is '%d'\n", printf("%p\n", ""));
	printf("Return value check for ptr addr and empty str. Ftprintf return value is '%d'\n", ft_printf("%p\n", ""));
	printf("\n\n");
	printf("Return value check for ptr addr and negative void ptr. Original return value is '%d'\n", printf("%p\n", (void *)-14523));
	printf("Return value check for ptr addr and negative void ptrr. Ftprintf return value is '%d'\n", ft_printf("%p\n", (void *)-14523));
	printf("\n\n");
	printf("Return value check for ptr addr and positive void ptr. Original return value is '%d'\n", printf("%p\n", (void *)14523));
	printf("Return value check for ptr addr and positive void ptr. Ftprintf return value is '%d'\n", ft_printf("%p\n", (void *)14523));
	printf("\n\n");
	printf("Return value check for ptr addr and LONGMIN & ULONGMAX void ptr. Original return value is '%d'\n", printf(" %p %p ", (void *)LONG_MIN, (void *)ULONG_MAX));
	printf("Return value check for ptr addr and LONGMIN & ULONGMAX void ptr. Ftprintf return value is '%d'\n", ft_printf(" %p %p ", (void *)LONG_MIN, (void *)ULONG_MAX));
	printf("\n\n");
	printf("Return value check for ptr addr and ULONGMAX void ptr. Original return value is '%d'\n", printf("0x%p\n", (void *)ULONG_MAX));
	printf("Return value check for ptr addr and ULONGMAX void ptr. Ftprintf return value is '%d'\n", ft_printf("0x%p\n", (void *)ULONG_MAX));
	printf("\n\n");
	printf("Return value check for RAND void ptrs. Original return value is '%d'\n", printf("%pp%p%p\n", (void *)LONG_MAX + 423856, (void *)0, (void *)INT_MAX));
	printf("Return value check for RAND void ptrs. Ftprintf return value is '%d'\n", ft_printf("%pp%p%p\n", (void *)LONG_MAX + 423856, (void *)0, (void *)INT_MAX));
	printf("\n\n");
	printf("\n\n");
	printf("\n\n");  
	printf ("%s \n","███████╗███████╗ ██████╗ █████╗ ██████╗ ███████╗    ██╗ ██╗██╗ ██╗");
	printf ("%s \n","██╔════╝██╔════╝██╔════╝██╔══██╗██╔══██╗██╔════╝    ╚═╝██╔╝╚═╝██╔╝");
	printf ("%s \n","█████╗  ███████╗██║     ███████║██████╔╝█████╗        ██╔╝   ██╔╝ ");
	printf ("%s \n","██╔══╝  ╚════██║██║     ██╔══██║██╔═══╝ ██╔══╝       ██╔╝   ██╔╝  ");
	printf ("%s \n","███████╗███████║╚██████╗██║  ██║██║     ███████╗    ██╔╝██╗██╔╝██╗");
	printf ("%s \n","╚══════╝╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝     ╚══════╝    ╚═╝ ╚═╝╚═╝ ╚═╝");
	printf("\n\n");  	
	printf("Return value check for %%. Original return value is '%d'\n", printf("%", 42));
	printf("\n");
	printf("Return value check for %%. Ftprintf return value is '%d'\n", ft_printf("%", 42));
	printf("\n\n");
	printf("Return value check for 2x%%. Original return value is '%d'\n", printf("%%\n"));
	printf("Return value check for 2x%%. Ftprintf return value is '%d'\n", ft_printf("%%\n"));
	printf("\n\n");
	printf("Return value check for 6x%%. Original return value is '%d'\n", printf ("%%%%%%\n"));
	printf("Return value check for 6x%%. Ftprintf return value is '%d'\n", ft_printf ("%%%%%%\n"));
	printf("\n\n");
	return 0;
}
